[workspace]
resolver = "2"
members = ["ch01", "ch02"]


[workspace.dependencies]
tokio = { version = "*", features = ["full"] }
reqwest = { version = "*", features = ["json", "cookies"] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
